[package]
name = "pl-update"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blocking = "1.4.0"
chrono = "0.4.38"
colored = "2.1.0"
os_info = "3.8.2"
regex = "1.10.5"
